version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: finance-tracker-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: finance_tracker
      MYSQL_USER: financeuser
      MYSQL_PASSWORD: financepass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - finance-tracker-network

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - finance-tracker-network

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka
    networks:
      - finance-tracker-network

volumes:
  mysql_data:

networks:
  finance-tracker-network:
    driver: bridge